# Generated by Django 4.0.4 on 2022-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
    ]
