# Generated by Django 4.0.4 on 2022-06-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_pedido_tipouser_alter_evento_fecha_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='idDetalle',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idpedido',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='tipouser',
            name='id_User',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='iduser',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(verbose_name='telefono'),
        ),
    ]
