# Generated by Django 4.0.4 on 2022-06-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_alter_evento_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_User', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tipoUsu', models.CharField(max_length=50, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='nombre')),
                ('Contrasenna', models.CharField(max_length=6, verbose_name='contrasenna')),
                ('correo', models.EmailField(max_length=254)),
                ('Fecha_nac', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.tipousuario')),
            ],
        ),
    ]
