# Generated by Django 4.0.4 on 2022-06-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_alter_evento_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetalle', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('fechaPedido', models.DateField()),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombrePedido', models.CharField(max_length=50, verbose_name='nombre_pedido')),
                ('stock', models.IntegerField(verbose_name='categoria_pedido')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_User', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tipoUsu', models.CharField(max_length=50, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='nombre')),
                ('Contrasenna', models.CharField(max_length=6, verbose_name='contrasenna')),
                ('correo', models.EmailField(max_length=254)),
                ('Fecha_nac', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.tipouser')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.user'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.pedido'),
        ),
    ]
