# Generated by Django 4.0.4 on 2022-06-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_detallepedido_pedido_tipouser_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombreUsuario',
            new_name='nombreUser',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='nombre')),
                ('Contrasenna', models.CharField(max_length=6, verbose_name='contrasenna')),
                ('Fecha_nac', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.tipouser')),
            ],
        ),
    ]
