# Generated by Django 4.0.4 on 2022-06-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_tipouser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetalle', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('fechaPedido', models.DateField()),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombrePedido', models.CharField(max_length=50, verbose_name='nombre_pedido')),
                ('stock', models.IntegerField(verbose_name='categoria_pedido')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.tipouser'),
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.user'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.pedido'),
        ),
    ]
