# Generated by Django 4.0.4 on 2022-06-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0007_alter_user_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useer',
            fields=[
                ('iduser', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='nombre')),
                ('Contrasenna', models.CharField(max_length=100, verbose_name='contrasenna')),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.tipouser')),
            ],
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='nombre_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.useer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
