# Generated by Django 4.0.4 on 2022-06-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_alter_evento_fecha'),
        ('musica', '0008_useer_alter_detallepedido_nombre_user_delete_user'),
    ]

    operations = [
    ]
