# Generated by Django 4.0.4 on 2022-06-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_tipousuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
