# Generated by Django 4.0.4 on 2022-07-10 19:10

from django.db import migrations, models
import musica.models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_useer_alter_detallepedido_nombre_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=musica.models.Pedido.url),
        ),
    ]
