# Generated by Django 4.0.4 on 2022-07-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0009_alter_pedido_imagen'),
        ('musica', '0009_merge_20220628_0026'),
    ]

    operations = [
    ]
